### ISSUE TITLE
Copy&Paste a Map does not work

### ISSUE THREAD

**Issue by rygos** [EasyRPG/Editor#144]
Hi,

I can't copy and paste a map. If I try to copy a map the paste icon is enabled. But If I try to paste a map I get the following message:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1985803/93820954-308e9f00-fc5e-11ea-9f63-3bba861d01d0.png">

**Comment by Ghabry** [comment]
Ohhhh, it seems that the Dark Mode detection works. I have a white and a dark item set.
I wrote ObjectiveC-Code just to query the MacOS dark mode flag..... naaaaaah. Just kidding. The algorithm is trivial:
I'm reading the background color and check if in HSL color space the lightness of the color is less than 128, then it is dark mode. :rofl:
