### ISSUE TITLE
Suggestion: Add some filters to cmake

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/Editor#172]
After creating the project with EDITOR_BUILD_LIBLCF there are 100+ header files and some are shown multiple times. For example `variables.h` and `terrain.h` is shown twice and `reader.h` is shown four times. This makes navigation and getting started quite hard.

**Comment by Ghabry** [comment]
Hm? Which program are you using? The one I use (qt creator) groups by folders

**Comment by Tondorian** [comment]
visual studio it only sorts header and source files and put the UI files into the project root

**Comment by carstene1ns** [comment]
Can you try applying this to CMakeLists.txt?

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4737d3f..9ac7974 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -15,7 +15,7 @@ set(CMAKE_CXX_STANDARD_REQUIRED ON)
 set(CMAKE_CXX_EXTENSIONS OFF)
 
 # Source Files
-add_library(${PROJECT_NAME} STATIC
+set(EDITOR_SOURCES
        src/common/dbstring.h
        src/common/filefinder.cpp
        src/common/filefinder.h
@@ -315,12 +315,16 @@ add_library(${PROJECT_NAME} STATIC
        src/ui/viewer/stat_curve_graphics_item.cpp
        src/ui/viewer/stat_curve_graphics_item.h
 )
+add_library(${PROJECT_NAME} STATIC ${EDITOR_SOURCES})
 
 # Include directories
 target_include_directories(${PROJECT_NAME} PUBLIC
        "${CMAKE_CURRENT_SOURCE_DIR}/src"
 )
 
+# IDE source grouping
+source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/src" PREFIX "Editor" FILES ${EDITOR_SOURCES})
+
 # Add autogen include dirs to include path, otherwise the includes are not found
 # when used in the header (via https://stackoverflow.com/q/44746308/)
 get_property(_isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
```

Unfortunately there is no cmake generator available on Linux to test this. :/

**Comment by Ghabry** [comment]
just tested. This works.
For some reason when using EDITOR_BUILD_LIBLCF then the Editor project also contains all the liblcf headers. This is obviously wrong but I do not know how to fix this. But with your source group it is at least in a different filter, so not as bad anymore.

**Comment by carstene1ns** [comment]
Maybe something like this can be done:
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9ac7974..16ae485 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -383,6 +383,9 @@ if(EDITOR_BUILD_LIBLCF)
                add_subdirectory(${LIBLCF_PATH})
        endfunction()
        add_liblcf()
+       # fixup IDE source grouping
+       get_target_property(LCF_SOURCES lcf SOURCES)
+       source_group(TREE "${LIBLCF_PATH}" PREFIX "liblcf" FILES ${LCF_SOURCES})
        target_link_libraries(${PROJECT_NAME} lcf)
 else()
        # Use system package
```

**Comment by Ghabry** [comment]
To get rid of the lcf header spam liblcf needs a patch.

```cmake
target_sources(lcf PRIVATE ${LCF_SOURCES} PUBLIC ${LCF_HEADERS})
```
The ``PUBLIC`` must be removed. The only use of ``PUBLIC`` for sources is if consumers of the library must compile something of there source files. Because we do not need this everything can be ``PRIVATE``.
See also this discussion: https://www.reddit.com/r/cmake/comments/881qd7/any_use_for_public_target_sources/

**Comment by carstene1ns** [comment]
Yeah, right. I confused this with the public api, but is only about sources. Will file a patch.
