### ISSUE TITLE
Error at building time

### ISSUE THREAD

**Issue by Fishaphrodite** [EasyRPG/Editor#173]
Hello, I tried building the editor today, and there was an error I actually saw before, and that error tells how to fix it as well.

During the make command:
```
[ 31%] Building CXX object CMakeFiles/EasyRPG_Editor.dir/src/ui/commands/change_vehicle_graphic_widget.cpp.o
In file included from /home/fishou/a_sources-git/EasyRPG/Editor/EasyRPG_Editor_autogen/include/ui_change_vehicle_graphic_widget.h:21,
                 from /home/fishou/a_sources-git/EasyRPG/Editor/src/ui/commands/change_vehicle_graphic_widget.cpp:19:
/home/fishou/a_sources-git/EasyRPG/Editor/src/ui/viewer/rpg_graphics_view.h:45:7: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   45 |  std::unique_ptr<QTimer> m_timer;
      |       ^~~~~~~~~~
/home/fishou/a_sources-git/EasyRPG/Editor/src/ui/viewer/rpg_graphics_view.h:29:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   28 | #include "faceset_graphics_item.h"
  +++ |+#include <memory>
   29 | 
make[2]: *** [CMakeFiles/EasyRPG_Editor.dir/build.make:531 : CMakeFiles/EasyRPG_Editor.dir/src/ui/commands/change_vehicle_graphic_widget.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:106 : CMakeFiles/EasyRPG_Editor.dir/all] Erreur 2
make: *** [Makefile:130 : all] Erreur 2
```
And indeed, adding the line `#include <memory>` in that `Editor/src/ui/viewer/rpg_graphics_view.h` file fixes it.

However, I can't really judge if it's the correct way to handle it or not, so I open an issue rather than making a PR. (not to mention that I'm not on top of my game today, so I prefer to avoid doing something requiring to think too much right now, one could argue building the editor is one of those things requiring to think, but it's pretty painless)

**Comment by carstene1ns** [comment]
This looks like it slipped through in #160.
Some newer compilers might be smart enough to not require this, but including the memory header is the way to go.

**Comment by Ghabry** [comment]
Hm 3 PR builders with 3 different C++ libraries and none catched this :/
