### ISSUE TITLE
Path to RTP Dialog Covered by Splash at Startup

### ISSUE THREAD

**Issue by AntumDeluge** [EasyRPG/Editor#211]
Path to RTP dialog is covered by splash screen & has to be moved before user can hit `Ok` or `Cancel` to open the main interface.

![image](https://user-images.githubusercontent.com/3631473/175901646-ed1617c6-d073-4242-9673-701ceff4ee10.png)

OS: Windows 10 64-bit
EasyRPG Editor build: from 342bbc7 with MinGW/GCC

**Comment by carstene1ns** [comment]
The RTP dialog triggers unfortunately a corner case in the logic I introduced. For the time being, build Editor in release mode, this should close the splash regardless if the dialog is open.

**Comment by AntumDeluge** [comment]
`-DCMAKE_BUILD_TYPE=Release`?

**Comment by Ghabry** [comment]
yes.


Btw do not expect too much.

There is a reason why we do not offer our own builds for it ;)

**Comment by carstene1ns** [comment]
Let's keep this open until it is really fixed. 😉
